spring:
  config:
    activate:
      on-profile: dev

  application:
    name: Ice-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gebase
    username: root
    password: xiaoleng

  # 失效时间
  # Session配置
  session:
    store-type: redis  # 使用Redis存储Session
    timeout: 86400     # Session超时时间（秒）
    redis:
      namespace: "ice:session"  # Redis中Session的命名空间
      flush-mode: on_save       # Session刷新模式

  # Redis配置
  redis:
    port: 6379
    host: localhost
    database: 1
    password: leng5201314
    timeout: 3000
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数
        max-idle: 8     # 连接池最大空闲连接数
        min-idle: 0     # 连接池最小空闲连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间
    # 新增缓存配置
    cache:
      # 默认过期时间（秒）
      default-ttl: 3600  # 1小时
      # 不同业务模块的过期时间
      ttl:
        user-recommend: 7200    # 用户推荐：2小时
        post-comment: 1800      # 帖子评论：30分钟
        user-info: 3600         # 用户信息：1小时
        team-info: 1800         # 队伍信息：30分钟

  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件的最大值
      max-file-size: 5MB # 单个文件上传的最大值

server:
  address: 0.0.0.0
  port: 9090
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 自动转化驼峰风格
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 腾讯云对象储存
cos:
  client:
    accessKey: AKIDd6KL7ewwmPo0xjHafW7TZQ2PYT9dwznL    # 腾讯云 SecretId
    secretKey: LRIuLXUXQ4SbVAd0LdiY9VbS3atKZZKq   # 腾讯云 SecretKey
    region: ap-chengdu  # 腾讯云 COS 所在区域
    bucket: xiaoleng-1333106413  # 腾讯云 COS Bucket 名称
file:
  cos:
    host: https://xiaoleng-1333106413.cos.ap-chengdu.myqcloud.com

